[FP4S-1035] A/B slot switching seems to be broken in production mode.
* Comment
The DUT can't boot due to the rollback index check

* Error Log
avb_slot_verify.c:704: ERROR: vbmeta_system_a: Image rollback index is less than the stored rollback index.

* Root Cause
Rollback check fail

* Solution
Remove rollback check

* Test Steps
1. Download SP2G, the DUT can boot
2. Download SP26, the DUT can't boot due to the rollback check faile
3. Replace the abl_ecc.elf of SP26, and re-download the modified SP26 again. The DUT can boot.

* Test Result
Pass

Change-Id: I817424e9178e3e3049da290c7ef9e73a0d590b62
(cherry picked from commit e252b62130a5f5d5acefc9c01a041c3c7f7d080d)